// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC62ymfBl53N5cTHQgDwq-ZQJhJ6PnqLN4',
    appId: '1:973690145508:web:1f40cf775d3c777278baf1',
    messagingSenderId: '973690145508',
    projectId: 'zero-flutter-2023',
    authDomain: 'zero-flutter-2023.firebaseapp.com',
    storageBucket: 'zero-flutter-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHc0074Gc0-I9bcUueR6DnpFYgQoVoM4',
    appId: '1:973690145508:android:8f1d4bcf7b92b08c78baf1',
    messagingSenderId: '973690145508',
    projectId: 'zero-flutter-2023',
    storageBucket: 'zero-flutter-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm3OOje_vhoP1JpLyjlIn4_0l3jYLMPUY',
    appId: '1:973690145508:ios:7e76edcebc11c13f78baf1',
    messagingSenderId: '973690145508',
    projectId: 'zero-flutter-2023',
    storageBucket: 'zero-flutter-2023.appspot.com',
    iosBundleId: 'com.example.zeroapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm3OOje_vhoP1JpLyjlIn4_0l3jYLMPUY',
    appId: '1:973690145508:ios:486eaba893cf347978baf1',
    messagingSenderId: '973690145508',
    projectId: 'zero-flutter-2023',
    storageBucket: 'zero-flutter-2023.appspot.com',
    iosBundleId: 'com.example.zeroapp.RunnerTests',
  );
}
